version: '3.8'
services:
  alfresco-mimetype-blocker-share:
    image: alfresco-share-alfresco-mimetype-blocker:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../alfresco-mimetype-blocker-share-docker/target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
      REPO_HOST: alfresco-mimetype-blocker-acs
      REPO_PORT: 8080
    ports:
      - "${share.port}:8080"
      - "${share.debug.port}:8888"
  alfresco-mimetype-blocker-acs:
    image: alfresco-content-services-alfresco-mimetype-blocker:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../alfresco-mimetype-blocker-platform-docker/target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
    ports:
      - "${acs.port}:8080"
      - "${acs.debug.port}:8888"
    volumes:
      - alfresco-mimetype-blocker-acs-volume:/usr/local/tomcat/alf_data
    depends_on:
      - alfresco-mimetype-blocker-postgres
  alfresco-mimetype-blocker-postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "${postgres.port}:5432"
    volumes:
      - alfresco-mimetype-blocker-db-volume:/var/lib/postgresql/data
  alfresco-mimetype-blocker-ass:
    image: alfresco/alfresco-search-services:1.4.3.2
    environment:
      #Solr needs to know how to register itself with Alfresco
      - SOLR_ALFRESCO_HOST=alfresco-mimetype-blocker-acs
      - SOLR_ALFRESCO_PORT=8080
      #Alfresco needs to know how to call solr
      - SOLR_SOLR_HOST=alfresco-mimetype-blocker-ass
      - SOLR_SOLR_PORT=8983
      #Create the default alfresco and archive cores
      - SOLR_CREATE_ALFRESCO_DEFAULTS=alfresco,archive
      #HTTP by default
      - ALFRESCO_SECURE_COMMS=none
    ports:
      - "8983:8983"
    volumes:
      - alfresco-mimetype-blocker-ass-volume:/opt/alfresco-search-services/contentstore
      - alfresco-mimetype-blocker-ass-volume:/opt/alfresco-search-services/data
volumes:
  alfresco-mimetype-blocker-acs-volume:
    external: true
  alfresco-mimetype-blocker-db-volume:
    external: true
  alfresco-mimetype-blocker-ass-volume:
    external: true